name: 'Upload app to TdA'
description: ''
author: 'Student Cyber Games'
inputs:
  artifact_name:
    description: 'The name artifact with docker image'
    required: true
  team_secret:
    description: 'Team secret'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.artifact_name }}
        path: /tmp/to_upload
    - name: Get Deploy Access
      id: deployAccess
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://api.tourdeapp.cz/get-auth'
        method: 'POST'
        data: '{"team_secret": "${{ inputs.team_secret }}"}'
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        registry: registry.tourdeapp.cz
        username: tda-user
        password: ${{ fromJson(steps.deployAccess.outputs.response).key }}
    - name: Load and push image
      env:
          IMAGE: ${{ fromJson(steps.deployAccess.outputs.response).name }}
      shell: bash
      run: |
        docker load --input /tmp/to_upload/*
        docker tag ${{ inputs.artifact_name }} $IMAGE
        docker push $IMAGE
