name: 'Upload app to TdA'
description: ''
author: 'Student Cyber Games'
inputs:
  path:
    description: 'The path of docker image'
    required: true
  team_secret:
    description: 'Team secret'
    required: true
runs:
  using: 'composite'
  runs-on: ubuntu-latest
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: myimage
        path: {{ inputs.path }}
    - name: Get Deploy Access
      id: deployAccess
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://api.tourdeapp.cz/get-auth'
        method: 'POST'
        data: '{"team_secret": "${{ input.team_secret }}"}'
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: tda-user
        password: fromJson(steps.deployAccess.outputs.response).key
    - name: Load and push image
      env:
          IMAGE: fromJson(steps.deployAccess.outputs.response).name
      run: |
        docker load --input /tmp/myimage.tar
        docker tag myimage $IMAGE
        docker push $IMAGE
