name: "Upload app to TdA"
description: "Upload action for the Tour de App competition"
author: "Student Cyber Games"
branding:
  color: orange
  icon: server
inputs:
  image_name:
    description: "Name of the Docker image"
    required: true
  image_path:
    description: "Path to the Docker image"
    required: true
  team_token:
    description: "Acces token"
    required: true
  base_domain:
    description: Base domain for the registry and authfish
    required: false
    default: "registry.tourde.app"
runs:
  using: "composite"
  steps:
    - name: Get image name
      id: deployAccess
      uses: fjogeleit/http-request-action@v1
      with:
        url: "https://authfish.${{ inputs.base_domain }}/container-info"
        method: "GET"
        customHeaders: '{"x-tda-token": "${{ inputs.team_token }}"}'

    - name: Load and push image
      env:
        IMAGE_NAME: ${{ fromJson(steps.deployAccess.outputs.response).image_name }}
        REGISTRY_URL: ${{ inputs.base_domain }}
        REGISTRY_PASSWORD: ${{ inputs.team_token }}
      shell: bash
      run: |
        docker login $REGISTRY_URL -u tour-de-upload-app -p $REGISTRY_PASSWORD
        docker load --input ${{ inputs.image_path }}
        docker tag ${{ inputs.image_name }} $REGISTRY_URL/$IMAGE_NAME
        docker push $REGISTRY_URL/$IMAGE_NAME
